// Grapheion — CASREP (Casualty Report) data model.
//
// A CASREP is generated by the DIVO from an active job and syncs over the mesh
// so the 3MC, CHENG, and Port Engineer see it without physical routing.

enum CasrepType { initial, update, cancel }

String casrepTypeToken(CasrepType t) => t.name;
CasrepType casrepTypeFromToken(String s) => CasrepType.values
    .firstWhere((t) => t.name == s, orElse: () => CasrepType.initial);

enum OpImpact { c1, c2, c3, c4 }

const opImpactLabel = {
  OpImpact.c1: 'C1 — No impact',
  OpImpact.c2: 'C2 — Degraded',
  OpImpact.c3: 'C3 — Significantly degraded',
  OpImpact.c4: 'C4 — Non-operational',
};

String opImpactToken(OpImpact o) => o.name;
OpImpact opImpactFromToken(String s) => OpImpact.values
    .firstWhere((o) => o.name == s, orElse: () => OpImpact.c2);

class Casrep {
  final String id;
  final String jobId;
  final String number; // zero-padded sequential, e.g. "003"
  CasrepType type;
  String hull; // ship hull designator, e.g. "DDG-51"
  String wuc; // Work Unit Code
  OpImpact opImpact;
  String etr; // estimated time to repair, free text e.g. "72 HRS"
  String narrative; // pre-filled from job symptom, editable
  String partsNeeded; // NSNs / nomenclature, optional free text
  final String originator;
  final int createdAtMs;
  int updatedAtMs;

  Casrep({
    required this.id,
    required this.jobId,
    required this.number,
    required this.type,
    required this.hull,
    required this.wuc,
    required this.opImpact,
    required this.etr,
    required this.narrative,
    required this.partsNeeded,
    required this.originator,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'jobId': jobId,
        'number': number,
        'type': casrepTypeToken(type),
        'hull': hull,
        'wuc': wuc,
        'opImpact': opImpactToken(opImpact),
        'etr': etr,
        'narrative': narrative,
        'partsNeeded': partsNeeded,
        'originator': originator,
        'createdAtMs': createdAtMs,
        'updatedAtMs': updatedAtMs,
      };

  factory Casrep.fromJson(Map<String, dynamic> j) => Casrep(
        id: j['id'] as String,
        jobId: (j['jobId'] ?? '') as String,
        number: (j['number'] ?? '000') as String,
        type: casrepTypeFromToken((j['type'] ?? 'initial') as String),
        hull: (j['hull'] ?? '') as String,
        wuc: (j['wuc'] ?? '') as String,
        opImpact: opImpactFromToken((j['opImpact'] ?? 'c2') as String),
        etr: (j['etr'] ?? '') as String,
        narrative: (j['narrative'] ?? '') as String,
        partsNeeded: (j['partsNeeded'] ?? '') as String,
        originator: (j['originator'] ?? '') as String,
        createdAtMs: (j['createdAtMs'] ?? 0) as int,
        updatedAtMs: (j['updatedAtMs'] ?? 0) as int,
      );

  String toMessageText() {
    final dt = DateTime.fromMillisecondsSinceEpoch(createdAtMs).toUtc();
    final months = [
      'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
      'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'
    ];
    final dtg =
        '${dt.day.toString().padLeft(2, '0')}${dt.hour.toString().padLeft(2, '0')}'
        '${dt.minute.toString().padLeft(2, '0')}Z ${months[dt.month - 1]} ${dt.year}';
    final lines = [
      'CASREP ${type.name.toUpperCase()} $hull SERIAL $number',
      'DTG: $dtg',
      'SYSTEM: $wuc',
      'OP IMPACT: ${opImpactLabel[opImpact]}',
      'ETR: ${etr.isEmpty ? 'TBD' : etr}',
      'NARRATIVE: $narrative',
      if (partsNeeded.isNotEmpty) 'PARTS/ASSIST REQ: $partsNeeded',
      'ORIGINATOR: $originator',
      'JOB REF: $jobId',
    ];
    return lines.join('\n');
  }
}
